version: "3.3"
services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: devdbpassword
      MYSQL_DATABASE: wp
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpressdevdbpassword
    restart: always

  wordpress:
    depends_on:
      - db
    image: wordpress:6.3
    volumes:
      - wordpress:/var/www/html
      - ./plugins/eee23-blocks:/var/www/html/wp-content/plugins/eee23-blocks
      - ./themes/eee-theme:/var/www/html/wp-content/themes/eee-theme
    ports:
      - "8086:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpressdevdbpassword
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        /* JS Script debug */
        define('SCRIPT_DEBUG', true );
    restart: always
  wp-cli:
    # To execute run: 'docker-wp <command>' ('docker compose run --rm wp-cli')
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    volumes_from:
      - wordpress
    user: 33:33
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpressdevdbpassword
      HOME: /tmp
    # command: tail -f /dev/null
    command: wp
volumes:
  db_data: {}
  wordpress:
