<?php
if(!defined('ABSPATH')) {
	exit; // Exit if accessed directly.
}

/**
 * EEE Theme 2023 functions and definitions
 */

/**
 * Theme setup: register editor styles for the iframed block editor (apiVersion 3).
 *
 * `add_editor_style()` injects the stylesheet directly into the isolated editor
 * iframe canvas so that custom block variation styles are visible while editing.
 *
 * @return void
 */
function eee_theme_23_setup(): void {
	add_editor_style( 'public/css/block-styles.css' );
}
add_action( 'after_setup_theme', 'eee_theme_23_setup' );


/**
 * Safely load asset metadata generated by @wordpress/scripts.
 *
 * @param string $relative_path Relative path to asset.php from theme directory.
 * @return array{dependencies: array<string>, version: string}
 */
function eee_theme_23_get_asset_metadata(string $relative_path): array {
	$file_path = get_parent_theme_file_path($relative_path);
	$theme_version = wp_get_theme()->get('Version');
	$default_version = (string) $theme_version;

	if (file_exists($file_path)) {
		$asset = include $file_path;
		if (is_array($asset)) {
			$dependencies = [];
			if (isset($asset['dependencies']) && is_array($asset['dependencies'])) {
				/** @var array<string> $dependencies */
				$dependencies = $asset['dependencies'];
			}

			$version = '' !== $default_version ? $default_version : '1.0.0';
			if (isset($asset['version']) && is_string($asset['version'])) {
				$version = $asset['version'];
			}

			return [
				'dependencies' => $dependencies,
				'version'      => $version,
			];
		}
	}

	return [
		'dependencies' => [],
		'version'      => '' !== $default_version ? $default_version : '1.0.0',
	];
}

if(!function_exists('eee_theme_23_styles')):

	/**
	 * Enqueue styles.
	 *
	 * @since Twenty Twenty-Two 1.0
	 *
	 * @return void
	 */
	function eee_theme_23_styles() {
		// Register theme stylesheet.
		$theme_version = wp_get_theme()->get('Version');

		$version_string = is_string($theme_version) ? $theme_version : false;
		wp_register_style(
			'eee_theme_23-style',
			get_template_directory_uri().'/style.css',
			array(),
			$version_string
		);

		// Enqueue theme stylesheet.
		wp_enqueue_style('eee_theme_23-style');

		$script_asset = eee_theme_23_get_asset_metadata('public/js/view.asset.php');
		// Add view.js script
		wp_register_script(
			'eee_theme_23-script',
			get_parent_theme_file_uri('public/js/view.js'),
			$script_asset['dependencies'],
			$script_asset['version'],
			true // add to footer
		);
		wp_enqueue_script('eee_theme_23-script');

	}

endif;

add_action('wp_enqueue_scripts', 'eee_theme_23_styles');

function eee_theme_23_add_editor_script(): void {
	$script_asset = eee_theme_23_get_asset_metadata('public/js/editor.asset.php');

	wp_enqueue_script(
		'eee-theme-23-editor',
		get_parent_theme_file_uri('public/js/editor.js'),
		$script_asset['dependencies'],
		$script_asset['version'],
		true
	);
}
add_action('enqueue_block_editor_assets', 'eee_theme_23_add_editor_script');

function eee_theme_23_block_styles(): void {
	$style_asset = eee_theme_23_get_asset_metadata('public/css/block-styles.asset.php');

	wp_register_style(
		'eee_theme_23-block-styles',
		get_parent_theme_file_uri('public/css/block-styles.css'),
		$style_asset['dependencies'],
		$style_asset['version'],
	);

	wp_enqueue_style('eee_theme_23-block-styles');
}
add_action('enqueue_block_assets', 'eee_theme_23_block_styles');


function eee_theme_23_include_svg_icons(): void {
	// Define SVG sprite file.
	$svg_icons = get_parent_theme_file_path('/assets/icons/svg-sprite.html');
	$svg_template = get_parent_theme_file_path('/assets/icons/svg-template.html');

	// If it exists, include it.
	if(file_exists($svg_icons) && file_exists($svg_template)) {
		require_once $svg_icons;
		require_once $svg_template;
	}
}
add_action('wp_footer', 'eee_theme_23_include_svg_icons', 9999);

function eee_theme_23_hkdev_user_can(mixed $capability): string {
	unset($capability);
	return 'edit_posts';
}
add_filter('hkdev_user_can', 'eee_theme_23_hkdev_user_can');
